#author-yaz c.


import turtle
turtle.bgcolor("sky blue")

pen = turtle.Turtle() #to set up a pen
#pen specifics
pen.pensize(2) #to change pen width
pen.color("gold")
pen.speed(0)
pen.hideturtle()

weather = turtle.textinput("Enter Sunny, Cloudy, Rainy, or Snowy: "," ").lower().strip()
sun = turtle.window_width()//4
arc_radius = 100



if weather == "sunny":
    pen.up()
    pen.setpos(0,-sun)
    pen.down()
    pen.begin_fill()
    pen.circle(sun)
    pen.end_fill()
elif weather == "cloudy":
    pen.up()
    pen.setpos(0,sun//2)
    pen.down()
    pen.begin_fill()
    pen.circle(sun//2)
    pen.end_fill()
    pen.up()
    pen.setpos(0,-sun//2)
    pen.down()
    pen.color("white")
    pen.begin_fill()
    pen.fillcolor("white")
    pen.setheading(-60)
    pen.circle(arc_radius,120)
    pen.setheading(0)
    pen.circle(arc_radius,120)
    pen.right(45)
    pen.circle(arc_radius,120)
    pen.right(45)
    pen.circle(arc_radius,120)
    pen.right(60)
    pen.circle(arc_radius,125)
    pen.end_fill()
elif weather == "rainy":
    pen.up()
    pen.setpos(0,-sun//3)
    pen.down()
    pen.color("blue")
    pen.begin_fill()
    pen.circle(arc_radius,120)
    pen.right(45)
    pen.circle(arc_radius,120)
    pen.right(45)
    pen.circle(arc_radius,150)
    pen.right(45)
    pen.circle(arc_radius,120)
    pen.right(45)
    pen.circle(arc_radius,120)
    pen.up()
    pen.setpos(sun*.7,sun*.5)
    pen.down()
    pen.circle(85)
    pen.end_fill()
    pen.up()
    pen.setpos(-sun//2,-sun//2)
    pen.down()
    pen.begin_fill()
    pen.circle(15)
    pen.end_fill()
    pen.up()
    pen.setheading(200)
    pen.forward(-sun//1.5)
    pen.down()
    pen.begin_fill()
    pen.circle(15)
    pen.end_fill()
    pen.up()
    pen.setpos(-sun//3,-sun//3)
    pen.down()
    pen.begin_fill()
    pen.circle(15)
    pen.end_fill()
    pen.up()
    pen.setpos(-sun//4,sun//3)
    pen.down()
    pen.begin_fill()
    pen.circle(15)
    pen.end_fill()
    pen.up()
    pen.setpos(-sun//2,-sun*1.2)
    pen.down()
    pen.begin_fill()
    pen.circle(15)
    pen.end_fill()
    pen.up()
    pen.setpos(-sun//2,-sun*.8)
    pen.down()
    pen.begin_fill()
    pen.circle(15)
    pen.end_fill()
    pen.up()
    pen.setpos(0,-sun)
    pen.down()
    pen.begin_fill()
    pen.circle(15)
    pen.end_fill()
    pen.up()
    pen.setpos(sun//10,-sun*.5)
    pen.down()
    pen.begin_fill()
    pen.circle(15)
    pen.end_fill()
elif weather == "snowy":
    pen.up()
    pen.color("white")
    pen.setpos(-sun//4,sun//4)
    pen.down()
    pen.begin_fill()
    pen.circle(arc_radius)
    pen.setheading(60)
    pen.circle(arc_radius)
    pen.setheading(100)
    pen.circle(arc_radius)
    pen.setheading(300)
    pen.circle(arc_radius)
    pen.setheading(270)
    pen.circle(arc_radius)
    pen.setheading(200)
    pen.circle(arc_radius//1.5)
    pen.end_fill()
    pen.up()
    pen.setpos(-sun*1.2,-sun*1.2)
    pen.down()
    pen.begin_fill()
    pen.circle(sun//10)
    pen.end_fill()
    pen.up()
    pen.setpos(-sun*.6,-sun*.6)
    pen.down
    pen.begin_fill()
    pen.circle(sun//10)
    pen.end_fill()
    pen.up()
    pen.setpos(-sun*.9,-sun*.9)
    pen.down()
    pen.begin_fill()
    pen.circle(sun//10)
    pen.end_fill()
    pen.up()
    pen.setpos(-sun,-sun*.5)
    pen.down()
    pen.begin_fill()
    pen.circle(sun//10)
    pen.end_fill()
    pen.up()
    pen.setpos(sun//2,-sun*.9)
    pen.down()
    pen.begin_fill()
    pen.circle(sun//10)
    pen.end_fill()
    pen.up()
    pen.setpos(sun//12,-sun*.5)
    pen.down()
    pen.begin_fill()
    pen.circle(sun//10)
    pen.end_fill()
    pen.up()
    pen.setpos(-sun//20,-sun*.8)
    pen.down()
    pen.begin_fill()
    pen.circle(sun//10)
    pen.end_fill()
    
    
    














turtle.done()


